replicaCount: 1
image:
  repository: ghcr.io/toeverything/affine
  pullPolicy: IfNotPresent
  tag: ''

imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
# map to NODE_ENV environment variable
env: 'production'
app:
  # AFFINE_SERVER_SUB_PATH
  path: ''
  # AFFINE_SERVER_HOST
  host: '0.0.0.0'
  https: true
serviceAccount:
  create: true
  annotations: {}
  name: 'affine-renderer'

podAnnotations: {}

podSecurityContext:
  fsGroup: 2000

resources:
  requests:
    cpu: '1'
    memory: 2Gi

probe:
  initialDelaySeconds: 20

nodeSelector: {}
tolerations: []
affinity: {}
