replicaCount: 1
image:
  repository: ghcr.io/toeverything/affine
  pullPolicy: IfNotPresent
  tag: ''

imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
# map to NODE_ENV environment variable
env: 'production'
app:
  # AFFINE_SERVER_HOST
  host: '0.0.0.0'
serviceAccount:
  create: true
  annotations: {}
  name: 'affine-sync'

podAnnotations: {}

podSecurityContext:
  fsGroup: 2000

resources:
  limits:
    cpu: '2'
    memory: 4Gi
  requests:
    cpu: '1'
    memory: 2Gi

probe:
  initialDelaySeconds: 20

nodeSelector: {}
tolerations: []
affinity: {}
